### ISSUE TITLE
Release as independent library

### ISSUE THREAD

**Issue by Gustl22** [twak/siteplan#3]
Hi Tom,

this is obviously an amazing project. Do you plan to release this as UI independent java library?
My concern is to use this as 3D building generation tool in a map renderer.
_Is there a forum to ask questions related to the implementation? Thanks!_

**Comment by twak** [comment]
Great, I would love to see the system used like this. I would warn you that the code is of "academic" grade - I do have a list of inputs that won't work.

I don't get enough interest in the project to justify a forum- please feel free to raise issues as tickets here/start your own forum (on reddit?)/[email me](https://engineering.leeds.ac.uk/staff/1545/Tom_Kelly_PhD_).

To simply stack weighted skeletons (without profiles etc...) you could use [campskeleton](https://github.com/twak/campskeleton) there's an example of how to do that [here](https://github.com/twak/campskeleton/blob/wiki/headless.md). I have no plans to release any other libraries - what functionality would you like to see?

Happy hacking!

**Comment by twak** [comment]
no reply; closed.

**Comment by Gustl22** [comment]
Thanks for your fast reply!
Sry for late response.
Indeed, I am using the profiles in my lib, so I think I have to go with siteplan.
I'll email you some questions :)
Thx for your help!
